name: Check OpenCode Version

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      has-new-version: ${{ steps.version-check.outputs.has-new-version }}
      current-version: ${{ steps.version-check.outputs.current-version }}
      latest-version: ${{ steps.version-check.outputs.latest-version }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check for new OpenCode version
        id: version-check
        run: |
          # Get current version from flake.nix
          CURRENT_VERSION=$(grep -o 'opencodeVersion = "[^"]*"' flake.nix | sed 's/opencodeVersion = "\(.*\)"/\1/')
          echo "Current version: $CURRENT_VERSION"
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Get latest version from npm registry
          LATEST_VERSION=$(curl -s https://registry.npmjs.org/opencode-ai | jq -r '.["dist-tags"].latest')
          echo "Latest version: $LATEST_VERSION"
          echo "latest-version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          
          # Compare versions
          if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
            echo "New version available: $LATEST_VERSION (current: $CURRENT_VERSION)"
            echo "has-new-version=true" >> $GITHUB_OUTPUT
          else
            echo "Already at latest version: $CURRENT_VERSION"
            echo "has-new-version=false" >> $GITHUB_OUTPUT
          fi