name: Scheduled OpenCode Update

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */6 * * *'  # Run at 00:15, 06:15, 12:15, 18:15 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || github.token }}
      
      - name: Setup Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Run Update
        run: |
          echo "Starting OpenCode update check..."
          nix --version
          echo "Workflow triggered by: ${{ github.event_name }}"
          echo "Current time: $(date)"
          # Add actual update logic here once workflow is confirmed working